// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr-gPzdjS5_gXpT3eySQUrXJ7ize_JWWU',
    appId: '1:299956056308:web:5b52c593437947dba9aea1',
    messagingSenderId: '299956056308',
    projectId: 'medicalqa-e5313',
    authDomain: 'medicalqa-e5313.firebaseapp.com',
    storageBucket: 'medicalqa-e5313.firebasestorage.app',
    measurementId: 'G-DXSREH8M4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD-tObyqkdjz6WfBFbuNaAqqM5ju0JS0c',
    appId: '1:299956056308:android:377044303745afe5a9aea1',
    messagingSenderId: '299956056308',
    projectId: 'medicalqa-e5313',
    storageBucket: 'medicalqa-e5313.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvmHMAK8BKz7xO_5hf3YwQCO8VtNyWVJE',
    appId: '1:299956056308:ios:f3771d8fce39efc9a9aea1',
    messagingSenderId: '299956056308',
    projectId: 'medicalqa-e5313',
    storageBucket: 'medicalqa-e5313.firebasestorage.app',
    iosBundleId: 'com.example.medicalQaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvmHMAK8BKz7xO_5hf3YwQCO8VtNyWVJE',
    appId: '1:299956056308:ios:f3771d8fce39efc9a9aea1',
    messagingSenderId: '299956056308',
    projectId: 'medicalqa-e5313',
    storageBucket: 'medicalqa-e5313.firebasestorage.app',
    iosBundleId: 'com.example.medicalQaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr-gPzdjS5_gXpT3eySQUrXJ7ize_JWWU',
    appId: '1:299956056308:web:23e88717d74b57a5a9aea1',
    messagingSenderId: '299956056308',
    projectId: 'medicalqa-e5313',
    authDomain: 'medicalqa-e5313.firebaseapp.com',
    storageBucket: 'medicalqa-e5313.firebasestorage.app',
    measurementId: 'G-KP79Z8TC6R',
  );

}